In [1]:
# 找到array的非零元素
import numpy as np

a = np.array([[1, 2, 0],
              [0, 4, 0],
              [1, 0, 0]])
idxs = np.where(a!=0)   # idxs = ([0, 0, 1, 2],[0, 1, 1, 0]) 手动也行^_^

# 行列数组索引
print(idxs)
print(a[idxs])

# 对应位置布尔类型索引
print(a!=0)
print(a[a!=0])

# 行列数组索引
print(a.nonzero())
print(a[a.nonzero()])

# 行列数组索引
print(np.nonzero(a))
print(a[np.nonzero(a)])

# 对应位置布尔类型索引
print(a!=0)
print(a[a!=0])

# 行列数组索引
print(a.nonzero())
print(a[a.nonzero()])

# 行列数组索引
print(np.nonzero(a))
print(a[np.nonzero(a)])

(array([0, 0, 1, 2]), array([0, 1, 1, 0]))
[1 2 4 1]
[[ True  True False]
 [False  True False]
 [ True False False]]
[1 2 4 1]
(array([0, 0, 1, 2]), array([0, 1, 1, 0]))
[1 2 4 1]
(array([0, 0, 1, 2]), array([0, 1, 1, 0]))
[1 2 4 1]
[[ True  True False]
 [False  True False]
 [ True False False]]
[1 2 4 1]
(array([0, 0, 1, 2]), array([0, 1, 1, 0]))
[1 2 4 1]
(array([0, 0, 1, 2]), array([0, 1, 1, 0]))
[1 2 4 1]


In [43]:
# 把np.where()返回的行列号分开的结果合并

a = np.array([[1, 2, 0],
              [0, 4, 0],
              [1, 0, 0]])
print("np.where(a)的初始返回结果：", np.where(a))

# ① 采用xzh的方案
def tuple2list(t):
    return [[t[0][idx], t[1][idx]] for idx in range(len(t[0]))]
rc = tuple2list(np.where(a))
print(rc)

# ② 使用zip
rc = []
for r, c in zip(*np.where(a)):  # 等价于for r, c in zip(np.where(a)[0], np.where(a)[1])
    rc.append([r, c])
print(rc)

# ③ 使用np的堆叠函数把两个分开的数组堆叠起来成为一个矩阵方便索引
rc = np.column_stack(np.where(a))
xy = rc[:, ::-1]
print(rc)
print(xy)

np.where(a)的初始返回结果： (array([0, 0, 1, 2]), array([0, 1, 1, 0]))
[[0, 0], [0, 1], [1, 1], [2, 0]]
[[0, 0], [0, 1], [1, 1], [2, 0]]
[[0 0]
 [0 1]
 [1 1]
 [2 0]]
[[0 0]
 [1 0]
 [1 1]
 [0 2]]


In [97]:
# 数组元素的排序与挑选
a = np.array([[7, 8, 0],
              [0, 9, 0],
              [7, 0, 0]])
print(np.argsort(a, axis=0))    # 数组元素沿指定轴排序，返回值在指定轴上的索引矩阵
print()

# print(np.sort(a, axis=0))    # 数组元素沿指定轴排序，返回具体值矩阵
# print()

print(np.take_along_axis(a, np.argsort(a, axis=0), axis=0))  # 根据返回的值的索引沿指定轴挑选元素（重排）
print()
b = np.zeros_like(a)
for j in range(a.shape[1]):
    b[:, j] = a[:, j][np.argsort(a, axis=0)[:,j]]
print(b)
print()


# # 只有一个轴式可以不使用take_along_axis函数
# a = np.array([7, 8, 0])
# print(np.argsort(a, axis=0))    # 数组元素沿指定轴排序，返回值在指定轴上的索引矩阵
# print()
# print(np.take_along_axis(a,np.argsort(a, axis=0), axis=0))
# print()

[[1 2 0]
 [0 0 1]
 [2 1 2]]

[[0 0 0]
 [7 8 0]
 [7 9 0]]

[[0 0 0]
 [7 8 0]
 [7 9 0]]



In [63]:
transform = lambda x: [i[::-1] for i in x]
a = [[1, 2], [3, 4]]
b = transform(a)
b

[[2, 1], [4, 3]]

In [65]:
a = np.linspace(0, 1, num=4+1, endpoint=True)
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [74]:
points = np.array([0, 1, 2, 3, 4, 5])
print(points[[0, 1, 4]])
print(points[[0, 1, 2, 3, 4, 5]])
print(points[[0, 1, 1, 1, 1, 1]])
print(points[np.bool_([0, 1, 1, 1, 1, 1])])

[0 1 4]
[0 1 2 3 4 5]
[0 1 1 1 1 1]
[1 2 3 4 5]
