In [1]:

import cv2 as cv
import numpy as np

img1 = np.zeros((11,11))
cv.line(img1, (0,5), (10,5), color=255, thickness=2)
img1

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])

In [2]:
from PIL import Image, ImageDraw

img2 = np.zeros((11,11))
img2 = Image.fromarray(img2).convert("RGB")
img_draw = ImageDraw.Draw(img2)
img_draw.line(((0,5), (10,5)), fill=255, width=3)
img = np.array(img2)[:,:,0]
img

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]],
      dtype=uint8)

In [3]:

# 看看samRoad和RNGDet的分割结果的统计数据如何

samRoad_mask_path = "/home/godx/research/source_code/sam_road/save/infer__20240427_172057/mask/8_road.png"
RNGDet_mask_paht = "/home/godx/research/RNGDet_test/RNGDetPlusPlus/cityscale/RNGDet_multi_ins/test/segmentation/8_segment.png"

# np.where()
sam_mask = np.array(Image.open(samRoad_mask_path))  # openCV保存的灰度图像，1通道
sam_mask = sam_mask[np.nonzero(sam_mask)]

RNG_mask = np.array(Image.open(RNGDet_mask_paht))[:,:,0]    # PIL保存的灰度图像（转换为了RGB，3通道）
RNG_mask = RNG_mask[RNG_mask.nonzero()]


print(f"SamRoad mean: {np.mean(sam_mask)}, std: {np.std(sam_mask)}")
print(f"RNGDet mean: {np.mean(RNG_mask)}, std: {np.std(RNG_mask)}")


FileNotFoundError: [Errno 2] No such file or directory: '/home/godx/research/RNGDet_test/RNGDetPlusPlus/cityscale/RNGDet_multi_ins/test/segmentation/8_segment.png'

In [ ]:

# 测试单通道的影像是否可以直接保存
# yes!

single_channel_img = np.ones((256, 256), dtype=np.uint8)*255
print(single_channel_img.shape)
Image.fromarray(single_channel_img).save("./single_cha_img.png")

single_channel_img = np.array(Image.open("./single_cha_img.png"))
print(single_channel_img.shape)

(256, 256)
(256, 256)


In [45]:

# 找到array的非零元素

a = np.array([[1, 2, 0],
              [0, 4, 0],
              [1, 0, 0]])
idxs = np.where(a!=0)   # idxs = ([0, 0, 1, 2],[0, 1, 1, 0]) 手动也行^_^

# 行列数组索引
print(idxs)
print(a[idxs])

# 对应位置布尔类型索引
print(a!=0)
print(a[a!=0])

# 行列数组索引
print(a.nonzero())
print(a[a.nonzero()])

# 行列数组索引
print(np.nonzero(a))
print(a[np.nonzero(a)])

# 对应位置布尔类型索引
print(a!=0)
print(a[a!=0])

# 行列数组索引
print(a.nonzero())
print(a[a.nonzero()])

# 行列数组索引
print(np.nonzero(a))
print(a[np.nonzero(a)])

(array([0, 0, 1, 2]), array([0, 1, 1, 0]))
[1 2 4 1]
[[ True  True False]
 [False  True False]
 [ True False False]]
[1 2 4 1]
(array([0, 0, 1, 2]), array([0, 1, 1, 0]))
[1 2 4 1]
(array([0, 0, 1, 2]), array([0, 1, 1, 0]))
[1 2 4 1]
[[ True  True False]
 [False  True False]
 [ True False False]]
[1 2 4 1]
(array([0, 0, 1, 2]), array([0, 1, 1, 0]))
[1 2 4 1]
(array([0, 0, 1, 2]), array([0, 1, 1, 0]))
[1 2 4 1]


In [43]:

# 把np.where()返回的行列号分开的结果合并
a = np.array([[1, 2, 0],
              [0, 4, 0],
              [1, 0, 0]])
print("np.where(a)的初始返回结果：", np.where(a))

# ① 采用xzh的方案
def tuple2list(t):
    return [[t[0][idx], t[1][idx]] for idx in range(len(t[0]))]
rc = tuple2list(np.where(a))
print(rc)

# ② 使用zip
rc = []
for r, c in zip(*np.where(a)):  # 等价于for r, c in zip(np.where(a)[0], np.where(a)[1])
    rc.append([r, c])
print(rc)

# ③ 使用np的堆叠函数把两个分开的数组堆叠起来成为一个矩阵方便索引
rc = np.column_stack(np.where(a))
xy = rc[:, ::-1]
print(rc)
print(xy)

np.where(a)的初始返回结果： (array([0, 0, 1, 2]), array([0, 1, 1, 0]))
[[0, 0], [0, 1], [1, 1], [2, 0]]
[[0, 0], [0, 1], [1, 1], [2, 0]]
[[0 0]
 [0 1]
 [1 1]
 [2 0]]
[[0 0]
 [1 0]
 [1 1]
 [0 2]]


In [62]:
a = np.array([[7, 8, 0],
              [0, 9, 0],
              [7, 0, 0]])


print(np.argsort(a, axis=0))
print()

print(np.sort(a, axis=0))
print()

print(np.take_along_axis(a, np.argsort(a, axis=0), 0))

[[1 2 0]
 [0 0 1]
 [2 1 2]]

[[0 0 0]
 [7 8 0]
 [7 9 0]]

[[0 0 0]
 [7 8 0]
 [7 9 0]]
